### ISSUE TITLE
Contextualise the validation exercises with security issues

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/error-handling-workshop#10]
The whole exercise is about validating input. 

Given that in foundersandcoders/master-reference#263 we agreed to redistribute some security topics throughout the rest of the curriculum, I think it would be a good idea to contextualise the exercise by explaining how validation fits into the security picture.

**Comment by eliascodes** [comment]
@njsfield are you happy for me to make these changes?

**Comment by njsfield** [comment]
@eliascodes sorry for the delay! That's cool- as I mentioned, I'm not an active maintainer for this workshop, it needs to grow for all important reasons....

Do you want to be maintainer?

**Comment by eliascodes** [comment]
@njsfield given the changes I'm proposing in #12 and #13 I suppose I might be considered de facto maintainer, but I would be keen to hand off to someone else soon.
