### ISSUE TITLE
solution is very complex - breakdown into simple first step

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/error-handling-workshop#16]
The solution is very well refactored and students didn't get very far with this workshop, so going through the solutions file at the end wasn't particularly illuminating.

@majakudlicka is going to run through a very simple piece of the `solutions` file, to demonstrate how to start going about the steps in the workshop:
1. `modules/validateFilename.js` - try catch function (Approach 1) which checks first part of spec i.e. must be a string
2. `tests/modules/validateFilename.test.js`
    + check whether entering numbers returns `false` with an error
    + check whether entering string returns `true`
3. `modules/handler.js`
    + run `validateFilename`
    + if result is invalid, return status code 400 & an error (Approach 2)
4. `tests/modules/index.test.js`
    + inject with payload whose filename is too long
    + check status code
    + check for error message

**Comment by jsms90** [comment]
https://github.com/majakudlicka/error-handling-workshop/tree/mysolution

**Comment by eliascodes** [comment]
Assuming this isn't going to get done.
