### ISSUE TITLE
Describe existing files

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/error-handling-workshop#20]
Based on feedback in #17 

Readers would benefit from a brief explanation of the pre-existing files for the exercise and how they relate.

**Comment by jsms90** [comment]
Specifically, to understand what `createRecord` is doing & how it relates to the handler

**Comment by eliascodes** [comment]
> * understanding what createRecord is doing and how it relates to the handler

It doesn't matter what it's doing. They should consider it a third party function. They just need to use it. Adding a note to this effect.

On how it relates to the handler, I thought it was implicit from:

> **Once the handler has validated the parameters** of the request **it should call** the provided `createRecord` function
> ...
> ... `message` contains the response to the client.

but have added another clarifying note.
