### ISSUE TITLE
Steps in the exercise are too big

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/error-handling-workshop#21]
Based on feedback from #17 

The steps in the exercise are too big for readers to work through effectively. Add more granular instructions.

**Comment by jsms90** [comment]
Maybe you don't want to make the steps any smaller. Perhaps it's just about clearer instructions, so that students understand how to fill in the gaps for themselves?

> + understanding that the "Steps" of the exercise are derived from the specification
>  + they created `validateFilename.js` because they were explicitly told to, rather than understanding that this is directly related to the first line in the requirements
>  + jump between step 2 & 3 - didn't understand that they would also need to create `validateContent.js` and `validate.js`
>  + problems understanding how `validateFilename.js` relates to the handler

**Comment by jsms90** [comment]
Or perhaps you could break it down into smaller steps and use each step to introduce one of the approaches?
