### ISSUE TITLE
provided solution doesn't match instructions - all in one file

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/error-handling-workshop#22]
Based on feedback from #17 

+ move content of `handler.solution.js` into multiple files
+ create tests

@eliascodes If it's ok with you, I think @majakudlicka and I might as well work on this, since some of the work has already been done via #16 and the extra sessions I've run with FAC11

**Comment by eliascodes** [comment]
@majakudlicka @jsms90 how's this coming? Should I still leave it to @majakudlicka or take it on myself?
