### ISSUE TITLE
make the first section (current non-exercise section) interactive

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/error-handling-workshop#28]
### why?
when delivered in Nazareth, students spent ages struggling with the long first section, and not really getting anywhere.

as mentors we stepped in (after quite a while) and casted writing some functions, and running them (on repl.it), one example for each of the 3 methods (throw, return, callback)- basically running through the README examples but slightly simpler.

### what 
I would suggest
- **making the REPL parts into exercises** that the students do.
- make the REPL parts more simple, e.g.
this:
```js
const applyAndPrintResult = (func, integer) => {
  try {
    const result = applyToInteger(func, integer);

    console.log('Result successfully calculated:');
    console.log(`Applying ${func.name} to ${integer} gives ${result}`);
  } catch (e) {
    console.log('Sorry, result could not be calculated:');
    console.log(e.message);
  }
}
```
is overcomplicated in my opinion, some people had never seen try/catch before and were completely lost by it being wrapped in a function. Show the examples without wrapping them in functions.
- the exercises should include how to write tests for a function which throws an error and an error-first callback function, as this is not straight-forward, students were confused by it, and it is required in the final exercise.

... or a big restructure of the workshop

**Comment by eliascodes** [comment]
This is kind of addressed by #30, will close this provisionally to see how it goes for this set of cohorts.
