### ISSUE TITLE
exercise1 part3: strech goal?

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/error-handling-workshop#38]
is exercise 1 part 3 intented to be a stretch goal? @eliascodes 

https://github.com/foundersandcoders/error-handling-workshop/blob/cc59088e1133141d73cde38b84a109fcedb2571a/exercises/approach-1/exercise.js#L43-L59

If so the "stretch goal" line should be moved up to the top of the snipper (as in the other exercises), otherwise the line should be removed.

**Comment by eliascodes** [comment]
No, looks like this is a mistake from when the order of exercises was moved around. In the original there was a fourth exercise, which was the stretch goal:

https://github.com/foundersandcoders/error-handling-workshop/blame/ffd6749766ff5320f66d8016a617932264c8aeb3/exercises/approach-1/exercise.js
