### ISSUE TITLE
Context around example approaches

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/error-handling-workshop#4]
The workshop proposes three approaches, but there is little to context provided about why one would or wouldn’t choose one above another. It would be really helpful to include some guidance like on these slides:
* https://github.com/rjmk/fac-error-talk/blob/master/008.md
* https://github.com/rjmk/fac-error-talk/blob/master/009.md
* https://github.com/rjmk/fac-error-talk/blob/master/018.md

**Comment by njsfield** [comment]
Perhaps at the end of each section *1. Error Throwing*, *2. Returning errors*, *3. Error first callbacks*, a section for 'Do Use When' and 'Don't Use When' with bullet point situations?

**Comment by eliascodes** [comment]
I think it's more important to understand what choosing each approach means for the rest of your code. 

For example, if you choose to throw, you must remember under what circumstances you might want to `catch`. If you choose to return errors, you must remember to place checks in your calling code. And so on.

These all have consequences for how you structure you whole codebase.
