### ISSUE TITLE
Providing test cases?

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/error-handling-workshop#5]
Did you find that having students specify their own test cases worked well? Did they cover all (or a sufficient number of) edge and failure cases?

If not, the alternative could be to provide a complete test suite for them. Their job would then only be to write enough code to result in a passing suite.

**Comment by njsfield** [comment]
>Did you find that having students specify their own test cases worked well? Did they cover all (or a sufficient number of) edge and failure cases?

Students spent a considerable amount of time in the exercise portion of the workshop writing tests for most cases outlined, and I remember that some students who chose to use the **error first callback** approach struggled writing their test assertions in a callback function...
```javascript
test('validateName', (t) => {
 validateName('john', (e, i) => {
   t.notok(e, 'error should not be returned')
   t.ok(i)
   ...
 })
})
```
>If not, the alternative could be to provide a complete test suite for them. Their job would then only be to write enough code to result in a passing suite.

I intended the *test-writing* portion of the exercises to be part of the challenge, as a core learning outcome for Node Week 2 was for students to feel more comfortable writing tests on the backend. Another learning outcome was for students to practice handling errors in different ways, so a solidified test suite would definitely work if the tests were mixed - i.e. some tests expecting *returned* result/errors and some expecting *callback* result/errors;
```javascript
// Return (validateAge)
test('validateAge', (t) => {
 t.equal(validateAge(3), true, 'should return true')
 ...
})

// Callback (validateName)
test('validateName', (t) => {
 validateName('john', (e, i) => {
   t.notok(e, 'error should not be returned')
 })
})
```
Do you think the workshop would be better to use the above approach and not focus on the test-writing learning outcome?

**Comment by eliascodes** [comment]
I don't know. I agree it's useful to get them practising writing tests. Only reason I asked is that if the developers are responsible for the tests as well as the code then the same assumptions will arise in both.

Another option might be to get them to write tests to help them while they're writing the functions, but afterwards have a set of acceptance tests that they run. This set should be complete in terms of input edge cases.

> Another learning outcome was for students to practice handling errors in different ways, so a solidified test suite would definitely work if the tests were mixed - i.e. some tests expecting returned result/errors and some expecting callback result/errors;

OK, this is fine for practice, but I would really emphasise consistency in chosen approach to handling errors. They shouldn't come out of the workshop thinking it's fine to mix approaches unless it's enforced (e.g. by the fact that one thing is async and one isn't).
